/*
* generated by Xtext
*/

package com.jaspersoft.studio.editor.jrexpressions.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class JavaJRExpressionGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final RuleCall cExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Model:
		//	Expression;
		public ParserRule getRule() { return rule; }

		//Expression
		public RuleCall getExpressionParserRuleCall() { return cExpressionParserRuleCall; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCreatorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cCastParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Assignment cCondExprAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cCondExprConditionalExpressionParserRuleCall_1_1_0 = (RuleCall)cCondExprAssignment_1_1.eContents().get(0);
		
		//Expression:
		//	Creator | Cast? condExpr=ConditionalExpression;
		public ParserRule getRule() { return rule; }

		//Creator | Cast? condExpr=ConditionalExpression
		public Alternatives getAlternatives() { return cAlternatives; }

		//Creator
		public RuleCall getCreatorParserRuleCall_0() { return cCreatorParserRuleCall_0; }

		//Cast? condExpr=ConditionalExpression
		public Group getGroup_1() { return cGroup_1; }

		//Cast?
		public RuleCall getCastParserRuleCall_1_0() { return cCastParserRuleCall_1_0; }

		//condExpr=ConditionalExpression
		public Assignment getCondExprAssignment_1_1() { return cCondExprAssignment_1_1; }

		//ConditionalExpression
		public RuleCall getCondExprConditionalExpressionParserRuleCall_1_1_0() { return cCondExprConditionalExpressionParserRuleCall_1_1_0; }
	}

	public class MethodInvocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MethodInvocation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMethodNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMethodNameQualifiedNameParserRuleCall_0_0 = (RuleCall)cMethodNameAssignment_0.eContents().get(0);
		private final Assignment cArgsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cArgsArgumentsParserRuleCall_1_0 = (RuleCall)cArgsAssignment_1.eContents().get(0);
		
		//MethodInvocation:
		//	methodName=QualifiedName args=Arguments;
		public ParserRule getRule() { return rule; }

		//methodName=QualifiedName args=Arguments
		public Group getGroup() { return cGroup; }

		//methodName=QualifiedName
		public Assignment getMethodNameAssignment_0() { return cMethodNameAssignment_0; }

		//QualifiedName
		public RuleCall getMethodNameQualifiedNameParserRuleCall_0_0() { return cMethodNameQualifiedNameParserRuleCall_0_0; }

		//args=Arguments
		public Assignment getArgsAssignment_1() { return cArgsAssignment_1; }

		//Arguments
		public RuleCall getArgsArgumentsParserRuleCall_1_0() { return cArgsArgumentsParserRuleCall_1_0; }
	}

	public class BaseJRExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BaseJRExpr");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cFieldTokenAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cFieldTokenFieldTokenTerminalRuleCall_0_0 = (RuleCall)cFieldTokenAssignment_0.eContents().get(0);
		private final Assignment cParameterTokenAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cParameterTokenParameterTokenTerminalRuleCall_1_0 = (RuleCall)cParameterTokenAssignment_1.eContents().get(0);
		private final Assignment cVariableTokenAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cVariableTokenVariableTokenTerminalRuleCall_2_0 = (RuleCall)cVariableTokenAssignment_2.eContents().get(0);
		
		//BaseJRExpr:
		//	fieldToken=FieldToken | parameterToken=ParameterToken | variableToken=VariableToken;
		public ParserRule getRule() { return rule; }

		//fieldToken=FieldToken | parameterToken=ParameterToken | variableToken=VariableToken
		public Alternatives getAlternatives() { return cAlternatives; }

		//fieldToken=FieldToken
		public Assignment getFieldTokenAssignment_0() { return cFieldTokenAssignment_0; }

		//FieldToken
		public RuleCall getFieldTokenFieldTokenTerminalRuleCall_0_0() { return cFieldTokenFieldTokenTerminalRuleCall_0_0; }

		//parameterToken=ParameterToken
		public Assignment getParameterTokenAssignment_1() { return cParameterTokenAssignment_1; }

		//ParameterToken
		public RuleCall getParameterTokenParameterTokenTerminalRuleCall_1_0() { return cParameterTokenParameterTokenTerminalRuleCall_1_0; }

		//variableToken=VariableToken
		public Assignment getVariableTokenAssignment_2() { return cVariableTokenAssignment_2; }

		//VariableToken
		public RuleCall getVariableTokenVariableTokenTerminalRuleCall_2_0() { return cVariableTokenVariableTokenTerminalRuleCall_2_0; }
	}

	public class ArgumentsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Arguments");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLeftPAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLeftPLPARENTerminalRuleCall_0_0 = (RuleCall)cLeftPAssignment_0.eContents().get(0);
		private final Assignment cExprLstAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExprLstExpressionListParserRuleCall_1_0 = (RuleCall)cExprLstAssignment_1.eContents().get(0);
		private final Assignment cRightPAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRightPRPARENTerminalRuleCall_2_0 = (RuleCall)cRightPAssignment_2.eContents().get(0);
		
		//Arguments:
		//	leftP=LPAREN exprLst=ExpressionList? rightP=RPAREN;
		public ParserRule getRule() { return rule; }

		//leftP=LPAREN exprLst=ExpressionList? rightP=RPAREN
		public Group getGroup() { return cGroup; }

		//leftP=LPAREN
		public Assignment getLeftPAssignment_0() { return cLeftPAssignment_0; }

		//LPAREN
		public RuleCall getLeftPLPARENTerminalRuleCall_0_0() { return cLeftPLPARENTerminalRuleCall_0_0; }

		//exprLst=ExpressionList?
		public Assignment getExprLstAssignment_1() { return cExprLstAssignment_1; }

		//ExpressionList
		public RuleCall getExprLstExpressionListParserRuleCall_1_0() { return cExprLstExpressionListParserRuleCall_1_0; }

		//rightP=RPAREN
		public Assignment getRightPAssignment_2() { return cRightPAssignment_2; }

		//RPAREN
		public RuleCall getRightPRPARENTerminalRuleCall_2_0() { return cRightPRPARENTerminalRuleCall_2_0; }
	}

	public class ExpressionListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExpressionList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cExpressionsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cExpressionsExpressionParserRuleCall_0_0 = (RuleCall)cExpressionsAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cCommasAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cCommasCOMMATerminalRuleCall_1_0_0 = (RuleCall)cCommasAssignment_1_0.eContents().get(0);
		private final Assignment cExpressionsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cExpressionsExpressionParserRuleCall_1_1_0 = (RuleCall)cExpressionsAssignment_1_1.eContents().get(0);
		
		//ExpressionList:
		//	expressions+=Expression (commas+=COMMA expressions+=Expression)*;
		public ParserRule getRule() { return rule; }

		//expressions+=Expression (commas+=COMMA expressions+=Expression)*
		public Group getGroup() { return cGroup; }

		//expressions+=Expression
		public Assignment getExpressionsAssignment_0() { return cExpressionsAssignment_0; }

		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_0_0() { return cExpressionsExpressionParserRuleCall_0_0; }

		//(commas+=COMMA expressions+=Expression)*
		public Group getGroup_1() { return cGroup_1; }

		//commas+=COMMA
		public Assignment getCommasAssignment_1_0() { return cCommasAssignment_1_0; }

		//COMMA
		public RuleCall getCommasCOMMATerminalRuleCall_1_0_0() { return cCommasCOMMATerminalRuleCall_1_0_0; }

		//expressions+=Expression
		public Assignment getExpressionsAssignment_1_1() { return cExpressionsAssignment_1_1; }

		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_1_1_0() { return cExpressionsExpressionParserRuleCall_1_1_0; }
	}

	public class BaseCommonExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BaseCommonExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cBasejrexprAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cBasejrexprBaseJRExprParserRuleCall_0_0 = (RuleCall)cBasejrexprAssignment_0.eContents().get(0);
		private final Assignment cLiteralAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cLiteralLiteralParserRuleCall_1_0 = (RuleCall)cLiteralAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final RuleCall cLPARENTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final RuleCall cRPARENTerminalRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		private final RuleCall cMethodInvocationParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//BaseCommonExpression returns Expression:
		//	basejrexpr=BaseJRExpr | literal=Literal | LPAREN Expression RPAREN | MethodInvocation;
		public ParserRule getRule() { return rule; }

		//basejrexpr=BaseJRExpr | literal=Literal | LPAREN Expression RPAREN | MethodInvocation
		public Alternatives getAlternatives() { return cAlternatives; }

		//basejrexpr=BaseJRExpr
		public Assignment getBasejrexprAssignment_0() { return cBasejrexprAssignment_0; }

		//BaseJRExpr
		public RuleCall getBasejrexprBaseJRExprParserRuleCall_0_0() { return cBasejrexprBaseJRExprParserRuleCall_0_0; }

		//literal=Literal
		public Assignment getLiteralAssignment_1() { return cLiteralAssignment_1; }

		//Literal
		public RuleCall getLiteralLiteralParserRuleCall_1_0() { return cLiteralLiteralParserRuleCall_1_0; }

		//LPAREN Expression RPAREN
		public Group getGroup_2() { return cGroup_2; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_2_0() { return cLPARENTerminalRuleCall_2_0; }

		//Expression
		public RuleCall getExpressionParserRuleCall_2_1() { return cExpressionParserRuleCall_2_1; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_2_2() { return cRPARENTerminalRuleCall_2_2; }

		//MethodInvocation
		public RuleCall getMethodInvocationParserRuleCall_3() { return cMethodInvocationParserRuleCall_3; }
	}

	public class CastElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Cast");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLparAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLparLPARENTerminalRuleCall_0_0 = (RuleCall)cLparAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cPtypeAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cPtypePrimitiveTypeParserRuleCall_1_0_0 = (RuleCall)cPtypeAssignment_1_0.eContents().get(0);
		private final Assignment cArrtypeAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cArrtypeArrayTypeParserRuleCall_1_1_0 = (RuleCall)cArrtypeAssignment_1_1.eContents().get(0);
		private final Assignment cClazztypeAssignment_1_2 = (Assignment)cAlternatives_1.eContents().get(2);
		private final RuleCall cClazztypeClassOrInterfaceTypeParserRuleCall_1_2_0 = (RuleCall)cClazztypeAssignment_1_2.eContents().get(0);
		private final Assignment cRparAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRparRPARENTerminalRuleCall_2_0 = (RuleCall)cRparAssignment_2.eContents().get(0);
		
		//Cast:
		//	lpar=LPAREN (ptype=PrimitiveType | arrtype=ArrayType | clazztype=ClassOrInterfaceType) rpar=RPAREN;
		public ParserRule getRule() { return rule; }

		//lpar=LPAREN (ptype=PrimitiveType | arrtype=ArrayType | clazztype=ClassOrInterfaceType) rpar=RPAREN
		public Group getGroup() { return cGroup; }

		//lpar=LPAREN
		public Assignment getLparAssignment_0() { return cLparAssignment_0; }

		//LPAREN
		public RuleCall getLparLPARENTerminalRuleCall_0_0() { return cLparLPARENTerminalRuleCall_0_0; }

		//ptype=PrimitiveType | arrtype=ArrayType | clazztype=ClassOrInterfaceType
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//ptype=PrimitiveType
		public Assignment getPtypeAssignment_1_0() { return cPtypeAssignment_1_0; }

		//PrimitiveType
		public RuleCall getPtypePrimitiveTypeParserRuleCall_1_0_0() { return cPtypePrimitiveTypeParserRuleCall_1_0_0; }

		//arrtype=ArrayType
		public Assignment getArrtypeAssignment_1_1() { return cArrtypeAssignment_1_1; }

		//ArrayType
		public RuleCall getArrtypeArrayTypeParserRuleCall_1_1_0() { return cArrtypeArrayTypeParserRuleCall_1_1_0; }

		//clazztype=ClassOrInterfaceType
		public Assignment getClazztypeAssignment_1_2() { return cClazztypeAssignment_1_2; }

		//ClassOrInterfaceType
		public RuleCall getClazztypeClassOrInterfaceTypeParserRuleCall_1_2_0() { return cClazztypeClassOrInterfaceTypeParserRuleCall_1_2_0; }

		//rpar=RPAREN
		public Assignment getRparAssignment_2() { return cRparAssignment_2; }

		//RPAREN
		public RuleCall getRparRPARENTerminalRuleCall_2_0() { return cRparRPARENTerminalRuleCall_2_0; }
	}

	public class ConditionalExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConditionalExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cTestExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cQuestionMarkKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cOkReturnedExprAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOkReturnedExprExpressionParserRuleCall_1_1_0 = (RuleCall)cOkReturnedExprAssignment_1_1.eContents().get(0);
		private final Keyword cColonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cKoReturnedExprAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cKoReturnedExprExpressionParserRuleCall_1_3_0 = (RuleCall)cKoReturnedExprAssignment_1_3.eContents().get(0);
		
		////primary:
		////	parExpression=parExpression
		////	| this='this'
		////	(dot+=DOT identifier+=IDENTIFIER)*
		////	(identifierSuffix=identifierSuffix)?
		////	| identifier+=IDENTIFIER
		////	(dot+=DOT identifier+=IDENTIFIER)*
		////	(identifierSuffix=identifierSuffix)?
		////	| 'super'
		////	superSuffix=superSuffix
		////	| literal=Literal
		////	| creator=Creator
		////	| primitiveType=PrimitiveType
		////	(lbrack+=LBRACKET rbrack+=RBRACKET)*
		////	dot+=DOT 'class'
		////	| 'void' dot+=DOT 'class';
		//// ========================== CONDITIONAL EXPRESSION STUFF ========================== //
		//ConditionalExpression returns Expression:
		//	TestExpression ("?" okReturnedExpr=Expression ":" koReturnedExpr=Expression)?;
		public ParserRule getRule() { return rule; }

		//TestExpression ("?" okReturnedExpr=Expression ":" koReturnedExpr=Expression)?
		public Group getGroup() { return cGroup; }

		//TestExpression
		public RuleCall getTestExpressionParserRuleCall_0() { return cTestExpressionParserRuleCall_0; }

		//("?" okReturnedExpr=Expression ":" koReturnedExpr=Expression)?
		public Group getGroup_1() { return cGroup_1; }

		//"?"
		public Keyword getQuestionMarkKeyword_1_0() { return cQuestionMarkKeyword_1_0; }

		//okReturnedExpr=Expression
		public Assignment getOkReturnedExprAssignment_1_1() { return cOkReturnedExprAssignment_1_1; }

		//Expression
		public RuleCall getOkReturnedExprExpressionParserRuleCall_1_1_0() { return cOkReturnedExprExpressionParserRuleCall_1_1_0; }

		//":"
		public Keyword getColonKeyword_1_2() { return cColonKeyword_1_2; }

		//koReturnedExpr=Expression
		public Assignment getKoReturnedExprAssignment_1_3() { return cKoReturnedExprAssignment_1_3; }

		//Expression
		public RuleCall getKoReturnedExprExpressionParserRuleCall_1_3_0() { return cKoReturnedExprExpressionParserRuleCall_1_3_0; }
	}

	public class TestExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TestExpression");
		private final RuleCall cOrExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//TestExpression returns Expression:
		//	OrExpression;
		public ParserRule getRule() { return rule; }

		//OrExpression
		public RuleCall getOrExpressionParserRuleCall() { return cOrExpressionParserRuleCall; }
	}

	public class OrExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OrExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAndExpAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAndExpAndExpressionParserRuleCall_0_0 = (RuleCall)cAndExpAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cVerticalLineVerticalLineKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAndExpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cAndExpAndExpressionParserRuleCall_1_1_0 = (RuleCall)cAndExpAssignment_1_1.eContents().get(0);
		
		//OrExpression returns Expression:
		//	andExp+=AndExpression ("||" andExp+=AndExpression)*;
		public ParserRule getRule() { return rule; }

		//andExp+=AndExpression ("||" andExp+=AndExpression)*
		public Group getGroup() { return cGroup; }

		//andExp+=AndExpression
		public Assignment getAndExpAssignment_0() { return cAndExpAssignment_0; }

		//AndExpression
		public RuleCall getAndExpAndExpressionParserRuleCall_0_0() { return cAndExpAndExpressionParserRuleCall_0_0; }

		//("||" andExp+=AndExpression)*
		public Group getGroup_1() { return cGroup_1; }

		//"||"
		public Keyword getVerticalLineVerticalLineKeyword_1_0() { return cVerticalLineVerticalLineKeyword_1_0; }

		//andExp+=AndExpression
		public Assignment getAndExpAssignment_1_1() { return cAndExpAssignment_1_1; }

		//AndExpression
		public RuleCall getAndExpAndExpressionParserRuleCall_1_1_0() { return cAndExpAndExpressionParserRuleCall_1_1_0; }
	}

	public class AndExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AndExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPrimaryCondAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPrimaryCondPrimaryCondExpressionParserRuleCall_0_0 = (RuleCall)cPrimaryCondAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAmpersandAmpersandKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cPrimaryCondAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cPrimaryCondPrimaryCondExpressionParserRuleCall_1_1_0 = (RuleCall)cPrimaryCondAssignment_1_1.eContents().get(0);
		
		//AndExpression returns Expression:
		//	primaryCond+=PrimaryCondExpression ("&&" primaryCond+=PrimaryCondExpression)*;
		public ParserRule getRule() { return rule; }

		//primaryCond+=PrimaryCondExpression ("&&" primaryCond+=PrimaryCondExpression)*
		public Group getGroup() { return cGroup; }

		//primaryCond+=PrimaryCondExpression
		public Assignment getPrimaryCondAssignment_0() { return cPrimaryCondAssignment_0; }

		//PrimaryCondExpression
		public RuleCall getPrimaryCondPrimaryCondExpressionParserRuleCall_0_0() { return cPrimaryCondPrimaryCondExpressionParserRuleCall_0_0; }

		//("&&" primaryCond+=PrimaryCondExpression)*
		public Group getGroup_1() { return cGroup_1; }

		//"&&"
		public Keyword getAmpersandAmpersandKeyword_1_0() { return cAmpersandAmpersandKeyword_1_0; }

		//primaryCond+=PrimaryCondExpression
		public Assignment getPrimaryCondAssignment_1_1() { return cPrimaryCondAssignment_1_1; }

		//PrimaryCondExpression
		public RuleCall getPrimaryCondPrimaryCondExpressionParserRuleCall_1_1_0() { return cPrimaryCondPrimaryCondExpressionParserRuleCall_1_1_0; }
	}

	public class PrimaryCondExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimaryCondExpression");
		private final Assignment cExprAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cExprBaseBooleanExprParserRuleCall_0 = (RuleCall)cExprAssignment.eContents().get(0);
		
		//PrimaryCondExpression returns Expression:
		//	expr=BaseBooleanExpr;
		public ParserRule getRule() { return rule; }

		//expr=BaseBooleanExpr
		public Assignment getExprAssignment() { return cExprAssignment; }

		//BaseBooleanExpr
		public RuleCall getExprBaseBooleanExprParserRuleCall_0() { return cExprBaseBooleanExprParserRuleCall_0; }
	}

	public class BaseBooleanExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BaseBooleanExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNOTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cEqualityExpressionParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//BaseBooleanExpr returns Expression:
		//	NOT? EqualityExpression;
		public ParserRule getRule() { return rule; }

		//NOT? EqualityExpression
		public Group getGroup() { return cGroup; }

		//NOT?
		public RuleCall getNOTTerminalRuleCall_0() { return cNOTTerminalRuleCall_0; }

		//EqualityExpression
		public RuleCall getEqualityExpressionParserRuleCall_1() { return cEqualityExpressionParserRuleCall_1; }
	}

	public class EqualityExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EqualityExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInstanceofAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cInstanceofInstanceOfExpressionParserRuleCall_0_0 = (RuleCall)cInstanceofAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final RuleCall cEQUALTerminalRuleCall_1_0_0 = (RuleCall)cAlternatives_1_0.eContents().get(0);
		private final RuleCall cNOTEQUALTerminalRuleCall_1_0_1 = (RuleCall)cAlternatives_1_0.eContents().get(1);
		private final Assignment cInstanceofAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cInstanceofInstanceOfExpressionParserRuleCall_1_1_0 = (RuleCall)cInstanceofAssignment_1_1.eContents().get(0);
		
		//// ========================== COMPARE EXPRESSIONS STUFF ========================== //
		//EqualityExpression returns Expression:
		//	instanceof+=InstanceOfExpression ((EQUAL | NOTEQUAL) instanceof+=InstanceOfExpression)*;
		public ParserRule getRule() { return rule; }

		//instanceof+=InstanceOfExpression ((EQUAL | NOTEQUAL) instanceof+=InstanceOfExpression)*
		public Group getGroup() { return cGroup; }

		//instanceof+=InstanceOfExpression
		public Assignment getInstanceofAssignment_0() { return cInstanceofAssignment_0; }

		//InstanceOfExpression
		public RuleCall getInstanceofInstanceOfExpressionParserRuleCall_0_0() { return cInstanceofInstanceOfExpressionParserRuleCall_0_0; }

		//((EQUAL | NOTEQUAL) instanceof+=InstanceOfExpression)*
		public Group getGroup_1() { return cGroup_1; }

		//EQUAL | NOTEQUAL
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }

		//EQUAL
		public RuleCall getEQUALTerminalRuleCall_1_0_0() { return cEQUALTerminalRuleCall_1_0_0; }

		//NOTEQUAL
		public RuleCall getNOTEQUALTerminalRuleCall_1_0_1() { return cNOTEQUALTerminalRuleCall_1_0_1; }

		//instanceof+=InstanceOfExpression
		public Assignment getInstanceofAssignment_1_1() { return cInstanceofAssignment_1_1; }

		//InstanceOfExpression
		public RuleCall getInstanceofInstanceOfExpressionParserRuleCall_1_1_0() { return cInstanceofInstanceOfExpressionParserRuleCall_1_1_0; }
	}

	public class RelationalExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RelationalExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cRelAdditiveExpressionParserRuleCall_0_0 = (RuleCall)cRelAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cRelationalOpParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Assignment cRelAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRelAdditiveExpressionParserRuleCall_1_1_0 = (RuleCall)cRelAssignment_1_1.eContents().get(0);
		
		//RelationalExpression returns Expression:
		//	rel+=AdditiveExpression (RelationalOp rel+=AdditiveExpression)*;
		public ParserRule getRule() { return rule; }

		//rel+=AdditiveExpression (RelationalOp rel+=AdditiveExpression)*
		public Group getGroup() { return cGroup; }

		//rel+=AdditiveExpression
		public Assignment getRelAssignment_0() { return cRelAssignment_0; }

		//AdditiveExpression
		public RuleCall getRelAdditiveExpressionParserRuleCall_0_0() { return cRelAdditiveExpressionParserRuleCall_0_0; }

		//(RelationalOp rel+=AdditiveExpression)*
		public Group getGroup_1() { return cGroup_1; }

		//RelationalOp
		public RuleCall getRelationalOpParserRuleCall_1_0() { return cRelationalOpParserRuleCall_1_0; }

		//rel+=AdditiveExpression
		public Assignment getRelAssignment_1_1() { return cRelAssignment_1_1; }

		//AdditiveExpression
		public RuleCall getRelAdditiveExpressionParserRuleCall_1_1_0() { return cRelAdditiveExpressionParserRuleCall_1_1_0; }
	}

	public class InstanceOfExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InstanceOfExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cElAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cElRelationalExpressionParserRuleCall_0_0 = (RuleCall)cElAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cINSTANCEOFTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Assignment cTargetAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cTargetAlternatives_1_1_0 = (Alternatives)cTargetAssignment_1_1.eContents().get(0);
		private final RuleCall cTargetRelationalExpressionParserRuleCall_1_1_0_0 = (RuleCall)cTargetAlternatives_1_1_0.eContents().get(0);
		private final RuleCall cTargetClassOrInterfaceTypeParserRuleCall_1_1_0_1 = (RuleCall)cTargetAlternatives_1_1_0.eContents().get(1);
		
		//InstanceOfExpression returns Expression:
		//	el=RelationalExpression (INSTANCEOF target=(RelationalExpression | ClassOrInterfaceType))?;
		public ParserRule getRule() { return rule; }

		//el=RelationalExpression (INSTANCEOF target=(RelationalExpression | ClassOrInterfaceType))?
		public Group getGroup() { return cGroup; }

		//el=RelationalExpression
		public Assignment getElAssignment_0() { return cElAssignment_0; }

		//RelationalExpression
		public RuleCall getElRelationalExpressionParserRuleCall_0_0() { return cElRelationalExpressionParserRuleCall_0_0; }

		//(INSTANCEOF target=(RelationalExpression | ClassOrInterfaceType))?
		public Group getGroup_1() { return cGroup_1; }

		//INSTANCEOF
		public RuleCall getINSTANCEOFTerminalRuleCall_1_0() { return cINSTANCEOFTerminalRuleCall_1_0; }

		//target=(RelationalExpression | ClassOrInterfaceType)
		public Assignment getTargetAssignment_1_1() { return cTargetAssignment_1_1; }

		//RelationalExpression | ClassOrInterfaceType
		public Alternatives getTargetAlternatives_1_1_0() { return cTargetAlternatives_1_1_0; }

		//RelationalExpression
		public RuleCall getTargetRelationalExpressionParserRuleCall_1_1_0_0() { return cTargetRelationalExpressionParserRuleCall_1_1_0_0; }

		//ClassOrInterfaceType
		public RuleCall getTargetClassOrInterfaceTypeParserRuleCall_1_1_0_1() { return cTargetClassOrInterfaceTypeParserRuleCall_1_1_0_1; }
	}

	public class AdditiveExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AdditiveExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMultExprAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMultExprMultiplicativeExpressionParserRuleCall_0_0 = (RuleCall)cMultExprAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_0_0 = (Keyword)cAlternatives_1_0.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_0_1 = (Keyword)cAlternatives_1_0.eContents().get(1);
		private final Assignment cMultExprAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cMultExprMultiplicativeExpressionParserRuleCall_1_1_0 = (RuleCall)cMultExprAssignment_1_1.eContents().get(0);
		
		//AdditiveExpression returns Expression:
		//	multExpr+=MultiplicativeExpression (("+" | "-") multExpr+=MultiplicativeExpression)*;
		public ParserRule getRule() { return rule; }

		//multExpr+=MultiplicativeExpression (("+" | "-") multExpr+=MultiplicativeExpression)*
		public Group getGroup() { return cGroup; }

		//multExpr+=MultiplicativeExpression
		public Assignment getMultExprAssignment_0() { return cMultExprAssignment_0; }

		//MultiplicativeExpression
		public RuleCall getMultExprMultiplicativeExpressionParserRuleCall_0_0() { return cMultExprMultiplicativeExpressionParserRuleCall_0_0; }

		//(("+" | "-") multExpr+=MultiplicativeExpression)*
		public Group getGroup_1() { return cGroup_1; }

		//"+" | "-"
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }

		//"+"
		public Keyword getPlusSignKeyword_1_0_0() { return cPlusSignKeyword_1_0_0; }

		//"-"
		public Keyword getHyphenMinusKeyword_1_0_1() { return cHyphenMinusKeyword_1_0_1; }

		//multExpr+=MultiplicativeExpression
		public Assignment getMultExprAssignment_1_1() { return cMultExprAssignment_1_1; }

		//MultiplicativeExpression
		public RuleCall getMultExprMultiplicativeExpressionParserRuleCall_1_1_0() { return cMultExprMultiplicativeExpressionParserRuleCall_1_1_0; }
	}

	public class MultiplicativeExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MultiplicativeExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBaseExprAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cBaseExprBaseCommonExpressionParserRuleCall_0_0 = (RuleCall)cBaseExprAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cDOTTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Assignment cMethodsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cMethodsMethodInvocationParserRuleCall_1_1_0 = (RuleCall)cMethodsAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_2_0 = (Alternatives)cGroup_2.eContents().get(0);
		private final Keyword cAsteriskKeyword_2_0_0 = (Keyword)cAlternatives_2_0.eContents().get(0);
		private final Keyword cSolidusKeyword_2_0_1 = (Keyword)cAlternatives_2_0.eContents().get(1);
		private final Assignment cBaseExprAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cBaseExprBaseCommonExpressionParserRuleCall_2_1_0 = (RuleCall)cBaseExprAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final RuleCall cDOTTerminalRuleCall_2_2_0 = (RuleCall)cGroup_2_2.eContents().get(0);
		private final Assignment cMethodsAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cMethodsMethodInvocationParserRuleCall_2_2_1_0 = (RuleCall)cMethodsAssignment_2_2_1.eContents().get(0);
		
		//MultiplicativeExpression returns Expression:
		//	baseExpr+=BaseCommonExpression (DOT methods+=MethodInvocation)* (("*" | "/") baseExpr+=BaseCommonExpression (DOT
		//	methods+=MethodInvocation)*)*;
		public ParserRule getRule() { return rule; }

		//baseExpr+=BaseCommonExpression (DOT methods+=MethodInvocation)* (("*" | "/") baseExpr+=BaseCommonExpression (DOT
		//methods+=MethodInvocation)*)*
		public Group getGroup() { return cGroup; }

		//baseExpr+=BaseCommonExpression
		public Assignment getBaseExprAssignment_0() { return cBaseExprAssignment_0; }

		//BaseCommonExpression
		public RuleCall getBaseExprBaseCommonExpressionParserRuleCall_0_0() { return cBaseExprBaseCommonExpressionParserRuleCall_0_0; }

		//(DOT methods+=MethodInvocation)*
		public Group getGroup_1() { return cGroup_1; }

		//DOT
		public RuleCall getDOTTerminalRuleCall_1_0() { return cDOTTerminalRuleCall_1_0; }

		//methods+=MethodInvocation
		public Assignment getMethodsAssignment_1_1() { return cMethodsAssignment_1_1; }

		//MethodInvocation
		public RuleCall getMethodsMethodInvocationParserRuleCall_1_1_0() { return cMethodsMethodInvocationParserRuleCall_1_1_0; }

		//(("*" | "/") baseExpr+=BaseCommonExpression (DOT methods+=MethodInvocation)*)*
		public Group getGroup_2() { return cGroup_2; }

		//"*" | "/"
		public Alternatives getAlternatives_2_0() { return cAlternatives_2_0; }

		//"*"
		public Keyword getAsteriskKeyword_2_0_0() { return cAsteriskKeyword_2_0_0; }

		//"/"
		public Keyword getSolidusKeyword_2_0_1() { return cSolidusKeyword_2_0_1; }

		//baseExpr+=BaseCommonExpression
		public Assignment getBaseExprAssignment_2_1() { return cBaseExprAssignment_2_1; }

		//BaseCommonExpression
		public RuleCall getBaseExprBaseCommonExpressionParserRuleCall_2_1_0() { return cBaseExprBaseCommonExpressionParserRuleCall_2_1_0; }

		//(DOT methods+=MethodInvocation)*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//DOT
		public RuleCall getDOTTerminalRuleCall_2_2_0() { return cDOTTerminalRuleCall_2_2_0; }

		//methods+=MethodInvocation
		public Assignment getMethodsAssignment_2_2_1() { return cMethodsAssignment_2_2_1; }

		//MethodInvocation
		public RuleCall getMethodsMethodInvocationParserRuleCall_2_2_1_0() { return cMethodsMethodInvocationParserRuleCall_2_2_1_0; }
	}

	public class RelationalOpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RelationalOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGTETerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLTTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLTETerminalRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//RelationalOp:
		//	GT | GTE | LT | LTE;
		public ParserRule getRule() { return rule; }

		//GT | GTE | LT | LTE
		public Alternatives getAlternatives() { return cAlternatives; }

		//GT
		public RuleCall getGTTerminalRuleCall_0() { return cGTTerminalRuleCall_0; }

		//GTE
		public RuleCall getGTETerminalRuleCall_1() { return cGTETerminalRuleCall_1; }

		//LT
		public RuleCall getLTTerminalRuleCall_2() { return cLTTerminalRuleCall_2; }

		//LTE
		public RuleCall getLTETerminalRuleCall_3() { return cLTETerminalRuleCall_3; }
	}

	public class CreatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Creator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cClassCreatorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cArrayCreatorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		////conditionalExpression:
		////	conditionalOrExpression=conditionalOrExpression
		////	('?' expression=Expression ':' conditionalExpression=conditionalExpression)?;
		////
		////conditionalOrExpression:
		////	conditionalAndExpression+=conditionalAndExpression
		////	('||' conditionalAndExpression+=conditionalAndExpression)*;
		////
		////conditionalAndExpression:
		////	inclusiveOrExpression+=inclusiveOrExpression
		////	('&&' inclusiveOrExpression+=inclusiveOrExpression)*;
		////
		////inclusiveOrExpression:
		////	exclusiveOrExpression+=exclusiveOrExpression
		////	('|' exclusiveOrExpression+=exclusiveOrExpression)*;
		////
		////exclusiveOrExpression:
		////	andExpression+=andExpression
		////	('^' andExpression+=andExpression)*;
		////
		////andExpression:
		////	equalityExpression+=equalityExpression
		////	('&' equalityExpression+=equalityExpression)*;
		////
		////equalityExpression:
		////	instanceOfExpression+=InstanceOfExpression
		////	(('=='
		////	| '!=')
		////	instanceOfExpression+=InstanceOfExpression)*;
		////
		////InstanceOfExpression:
		////	relationalExpression=relationalExpression
		////	('instanceof' type=Type)?;
		////
		////relationalExpression:
		////	shiftExpression+=shiftExpression
		////	(relationalOp shiftExpression+=shiftExpression)*;
		////
		////terminal relationalOp:
		////	'<' '='
		////	| '>' '='
		////	| '<'
		////	| '>';
		////
		////shiftExpression 
		////    :   additiveExpression+=additiveExpression
		////        (shiftOp additiveExpression+=additiveExpression
		////        )*
		////    ;
		////
		////terminal shiftOp:
		////	'<' '<'
		////	| '>' '>' '>'
		////	| '>' '>';
		////
		////
		////additiveExpression:
		////	multiplicativeExpression+=multiplicativeExpression
		////	(('+'
		////	| '-')
		////	multiplicativeExpression+=multiplicativeExpression)*;
		////
		////multiplicativeExpression:
		////	unaryExpression+=unaryExpression
		////	(('*'
		////	| '/'
		////	| '%')
		////	unaryExpression+=unaryExpression)*;
		////
		///// **
		//// * NOTE: for '+' and '-', if the next token is int or long interal, then it's not a unary expression.
		//// *       it's a literal with signed value. INTLTERAL AND LONG LITERAL are added here for this.
		//// * /
		////unaryExpression:
		////	'+' unaryExpression=unaryExpression
		////	| '-' unaryExpression=unaryExpression
		////	| '++' unaryExpression=unaryExpression
		////	| '--' unaryExpression=unaryExpression
		////	| unaryExpressionNotPlusMinus;
		////
		////unaryExpressionNotPlusMinus:
		////	'~' unaryExpression=unaryExpression
		////	| '!' unaryExpression=unaryExpression
		////	| castExpression=CastExpression
		////	| primary
		////	(selector+=selector)*
		////	('++'
		////	| '--')?;
		////	
		////primary:
		////	parExpression=parExpression
		////	| this='this'
		////	(dot+=DOT identifier+=IDENTIFIER)*
		////	(identifierSuffix=identifierSuffix)?
		////	| identifier+=IDENTIFIER
		////	(dot+=DOT identifier+=IDENTIFIER)*
		////	(identifierSuffix=identifierSuffix)?
		////	| 'super'
		////	superSuffix=superSuffix
		////	| literal=Literal
		////	| creator=Creator
		////	| primitiveType=PrimitiveType
		////	(lbrack+=LBRACKET rbrack+=RBRACKET)*
		////	dot+=DOT 'class'
		////	| 'void' dot+=DOT 'class';
		////
		////parExpression 
		////    :   LPAREN Expression RPAREN
		////    ;
		////
		////superSuffix:
		////	Arguments
		////	| dot=DOT
		////	identifier=IDENTIFIER
		////	(arguments=Arguments)?;
		////
		////
		////identifierSuffix:
		////	(LBRACKET RBRACKET)+
		////	dot+=DOT 'class'
		////	| (LBRACKET expression+=Expression RBRACKET)+
		////	| arguments=Arguments
		////	| dot+=DOT 'class'
		////	| dot+=DOT IDENTIFIER arguments=Arguments
		////	| dot+=DOT 'this'
		////	| dot+=DOT 'super' arguments=Arguments
		////	| innerCreator=InnerCreator;
		////
		////selector:
		////	dot=DOT identifier=IDENTIFIER
		////	(arguments=Arguments)?
		////	| dot=DOT 'this'
		////	| dot=DOT 'super'
		////	superSuffix=superSuffix
		////	| innerCreator=InnerCreator
		////	| LBRACKET expression=Expression RBRACKET;	
		//Creator:
		//	ClassCreator | ArrayCreator;
		public ParserRule getRule() { return rule; }

		//ClassCreator | ArrayCreator
		public Alternatives getAlternatives() { return cAlternatives; }

		//ClassCreator
		public RuleCall getClassCreatorParserRuleCall_0() { return cClassCreatorParserRuleCall_0; }

		//ArrayCreator
		public RuleCall getArrayCreatorParserRuleCall_1() { return cArrayCreatorParserRuleCall_1; }
	}

	public class ClassCreatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ClassCreator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNEWTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cClazzAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cClazzClassOrInterfaceTypeParserRuleCall_1_0 = (RuleCall)cClazzAssignment_1.eContents().get(0);
		private final Assignment cArgsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cArgsArgumentsParserRuleCall_2_0 = (RuleCall)cArgsAssignment_2.eContents().get(0);
		
		//ClassCreator:
		//	NEW clazz=ClassOrInterfaceType args=Arguments;
		public ParserRule getRule() { return rule; }

		//NEW clazz=ClassOrInterfaceType args=Arguments
		public Group getGroup() { return cGroup; }

		//NEW
		public RuleCall getNEWTerminalRuleCall_0() { return cNEWTerminalRuleCall_0; }

		//clazz=ClassOrInterfaceType
		public Assignment getClazzAssignment_1() { return cClazzAssignment_1; }

		//ClassOrInterfaceType
		public RuleCall getClazzClassOrInterfaceTypeParserRuleCall_1_0() { return cClazzClassOrInterfaceTypeParserRuleCall_1_0; }

		//args=Arguments
		public Assignment getArgsAssignment_2() { return cArgsAssignment_2; }

		//Arguments
		public RuleCall getArgsArgumentsParserRuleCall_2_0() { return cArgsArgumentsParserRuleCall_2_0; }
	}

	public class ArrayCreatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ArrayCreator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNEWTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeArrayTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cArrayInitializerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cArrayInitializerArrayInitializerParserRuleCall_2_0 = (RuleCall)cArrayInitializerAssignment_2.eContents().get(0);
		
		//ArrayCreator:
		//	NEW type=ArrayType arrayInitializer=ArrayInitializer;
		public ParserRule getRule() { return rule; }

		//NEW type=ArrayType arrayInitializer=ArrayInitializer
		public Group getGroup() { return cGroup; }

		//NEW
		public RuleCall getNEWTerminalRuleCall_0() { return cNEWTerminalRuleCall_0; }

		//type=ArrayType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }

		//ArrayType
		public RuleCall getTypeArrayTypeParserRuleCall_1_0() { return cTypeArrayTypeParserRuleCall_1_0; }

		//arrayInitializer=ArrayInitializer
		public Assignment getArrayInitializerAssignment_2() { return cArrayInitializerAssignment_2; }

		//ArrayInitializer
		public RuleCall getArrayInitializerArrayInitializerParserRuleCall_2_0() { return cArrayInitializerArrayInitializerParserRuleCall_2_0; }
	}

	public class ArrayInitializerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ArrayInitializer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArrayInitializerAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cLBRACETerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cFirstElAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cFirstElExpressionParserRuleCall_2_0_0 = (RuleCall)cFirstElAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final RuleCall cCOMMATerminalRuleCall_2_1_0 = (RuleCall)cGroup_2_1.eContents().get(0);
		private final Assignment cOtherElsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cOtherElsExpressionParserRuleCall_2_1_1_0 = (RuleCall)cOtherElsAssignment_2_1_1.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cRBRACETerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//ArrayInitializer:
		//	{ArrayInitializer} LBRACE (firstEl=Expression (COMMA otherEls+=Expression)*)? COMMA? RBRACE;
		public ParserRule getRule() { return rule; }

		//{ArrayInitializer} LBRACE (firstEl=Expression (COMMA otherEls+=Expression)*)? COMMA? RBRACE
		public Group getGroup() { return cGroup; }

		//{ArrayInitializer}
		public Action getArrayInitializerAction_0() { return cArrayInitializerAction_0; }

		//LBRACE
		public RuleCall getLBRACETerminalRuleCall_1() { return cLBRACETerminalRuleCall_1; }

		//(firstEl=Expression (COMMA otherEls+=Expression)*)?
		public Group getGroup_2() { return cGroup_2; }

		//firstEl=Expression
		public Assignment getFirstElAssignment_2_0() { return cFirstElAssignment_2_0; }

		//Expression
		public RuleCall getFirstElExpressionParserRuleCall_2_0_0() { return cFirstElExpressionParserRuleCall_2_0_0; }

		//(COMMA otherEls+=Expression)*
		public Group getGroup_2_1() { return cGroup_2_1; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_2_1_0() { return cCOMMATerminalRuleCall_2_1_0; }

		//otherEls+=Expression
		public Assignment getOtherElsAssignment_2_1_1() { return cOtherElsAssignment_2_1_1; }

		//Expression
		public RuleCall getOtherElsExpressionParserRuleCall_2_1_1_0() { return cOtherElsExpressionParserRuleCall_2_1_1_0; }

		//COMMA?
		public RuleCall getCOMMATerminalRuleCall_3() { return cCOMMATerminalRuleCall_3; }

		//RBRACE
		public RuleCall getRBRACETerminalRuleCall_4() { return cRBRACETerminalRuleCall_4; }
	}

	public class InnerCreatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InnerCreator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDOTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cNEWTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final RuleCall cIDENTIFIERTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cArgsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cArgsArgumentsParserRuleCall_3_0 = (RuleCall)cArgsAssignment_3.eContents().get(0);
		
		//InnerCreator:
		//	DOT NEW IDENTIFIER args=Arguments;
		public ParserRule getRule() { return rule; }

		//DOT NEW IDENTIFIER args=Arguments
		public Group getGroup() { return cGroup; }

		//DOT
		public RuleCall getDOTTerminalRuleCall_0() { return cDOTTerminalRuleCall_0; }

		//NEW
		public RuleCall getNEWTerminalRuleCall_1() { return cNEWTerminalRuleCall_1; }

		//IDENTIFIER
		public RuleCall getIDENTIFIERTerminalRuleCall_2() { return cIDENTIFIERTerminalRuleCall_2; }

		//args=Arguments
		public Assignment getArgsAssignment_3() { return cArgsAssignment_3; }

		//Arguments
		public RuleCall getArgsArgumentsParserRuleCall_3_0() { return cArgsArgumentsParserRuleCall_3_0; }
	}

	public class ArrayTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ArrayType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Assignment cClazzInterfAssignment_0_0 = (Assignment)cAlternatives_0.eContents().get(0);
		private final RuleCall cClazzInterfClassOrInterfaceTypeParserRuleCall_0_0_0 = (RuleCall)cClazzInterfAssignment_0_0.eContents().get(0);
		private final Assignment cPrimtypeAssignment_0_1 = (Assignment)cAlternatives_0.eContents().get(1);
		private final RuleCall cPrimtypePrimitiveTypeParserRuleCall_0_1_0 = (RuleCall)cPrimtypeAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cLBRACKETTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final RuleCall cRBRACKETTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//ArrayType:
		//	(clazzInterf=ClassOrInterfaceType | primtype=PrimitiveType) (LBRACKET RBRACKET)+;
		public ParserRule getRule() { return rule; }

		//(clazzInterf=ClassOrInterfaceType | primtype=PrimitiveType) (LBRACKET RBRACKET)+
		public Group getGroup() { return cGroup; }

		//clazzInterf=ClassOrInterfaceType | primtype=PrimitiveType
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//clazzInterf=ClassOrInterfaceType
		public Assignment getClazzInterfAssignment_0_0() { return cClazzInterfAssignment_0_0; }

		//ClassOrInterfaceType
		public RuleCall getClazzInterfClassOrInterfaceTypeParserRuleCall_0_0_0() { return cClazzInterfClassOrInterfaceTypeParserRuleCall_0_0_0; }

		//primtype=PrimitiveType
		public Assignment getPrimtypeAssignment_0_1() { return cPrimtypeAssignment_0_1; }

		//PrimitiveType
		public RuleCall getPrimtypePrimitiveTypeParserRuleCall_0_1_0() { return cPrimtypePrimitiveTypeParserRuleCall_0_1_0; }

		//(LBRACKET RBRACKET)+
		public Group getGroup_1() { return cGroup_1; }

		//LBRACKET
		public RuleCall getLBRACKETTerminalRuleCall_1_0() { return cLBRACKETTerminalRuleCall_1_0; }

		//RBRACKET
		public RuleCall getRBRACKETTerminalRuleCall_1_1() { return cRBRACKETTerminalRuleCall_1_1; }
	}

	public class ClassOrInterfaceTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ClassOrInterfaceType");
		private final Assignment cQualifiedNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cQualifiedNameQualifiedNameParserRuleCall_0 = (RuleCall)cQualifiedNameAssignment.eContents().get(0);
		
		//ClassOrInterfaceType:
		//	qualifiedName=QualifiedName;
		public ParserRule getRule() { return rule; }

		//qualifiedName=QualifiedName
		public Assignment getQualifiedNameAssignment() { return cQualifiedNameAssignment; }

		//QualifiedName
		public RuleCall getQualifiedNameQualifiedNameParserRuleCall_0() { return cQualifiedNameQualifiedNameParserRuleCall_0; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQualifiedNameAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIdentifierAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdentifierIDENTIFIERTerminalRuleCall_1_0 = (RuleCall)cIdentifierAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cDotAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cDotDOTTerminalRuleCall_2_0_0 = (RuleCall)cDotAssignment_2_0.eContents().get(0);
		private final Assignment cIdentifierAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdentifierIDENTIFIERTerminalRuleCall_2_1_0 = (RuleCall)cIdentifierAssignment_2_1.eContents().get(0);
		
		//QualifiedName:
		//	{QualifiedName} identifier+=IDENTIFIER (dot+=DOT identifier+=IDENTIFIER)*;
		public ParserRule getRule() { return rule; }

		//{QualifiedName} identifier+=IDENTIFIER (dot+=DOT identifier+=IDENTIFIER)*
		public Group getGroup() { return cGroup; }

		//{QualifiedName}
		public Action getQualifiedNameAction_0() { return cQualifiedNameAction_0; }

		//identifier+=IDENTIFIER
		public Assignment getIdentifierAssignment_1() { return cIdentifierAssignment_1; }

		//IDENTIFIER
		public RuleCall getIdentifierIDENTIFIERTerminalRuleCall_1_0() { return cIdentifierIDENTIFIERTerminalRuleCall_1_0; }

		//(dot+=DOT identifier+=IDENTIFIER)*
		public Group getGroup_2() { return cGroup_2; }

		//dot+=DOT
		public Assignment getDotAssignment_2_0() { return cDotAssignment_2_0; }

		//DOT
		public RuleCall getDotDOTTerminalRuleCall_2_0_0() { return cDotDOTTerminalRuleCall_2_0_0; }

		//identifier+=IDENTIFIER
		public Assignment getIdentifierAssignment_2_1() { return cIdentifierAssignment_2_1; }

		//IDENTIFIER
		public RuleCall getIdentifierIDENTIFIERTerminalRuleCall_2_1_0() { return cIdentifierIDENTIFIERTerminalRuleCall_2_1_0; }
	}

	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Literal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTLITERALTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLONGLITERALTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFLOATLITERALTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDOUBLELITERALTerminalRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cCHARLITERALTerminalRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cSTRINGLITERALTerminalRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cTRUETerminalRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cFALSETerminalRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cNULLTerminalRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		
		//Literal:
		//	INTLITERAL | LONGLITERAL | FLOATLITERAL | DOUBLELITERAL | CHARLITERAL | STRINGLITERAL | TRUE | FALSE | NULL;
		public ParserRule getRule() { return rule; }

		//INTLITERAL | LONGLITERAL | FLOATLITERAL | DOUBLELITERAL | CHARLITERAL | STRINGLITERAL | TRUE | FALSE | NULL
		public Alternatives getAlternatives() { return cAlternatives; }

		//INTLITERAL
		public RuleCall getINTLITERALTerminalRuleCall_0() { return cINTLITERALTerminalRuleCall_0; }

		//LONGLITERAL
		public RuleCall getLONGLITERALTerminalRuleCall_1() { return cLONGLITERALTerminalRuleCall_1; }

		//FLOATLITERAL
		public RuleCall getFLOATLITERALTerminalRuleCall_2() { return cFLOATLITERALTerminalRuleCall_2; }

		//DOUBLELITERAL
		public RuleCall getDOUBLELITERALTerminalRuleCall_3() { return cDOUBLELITERALTerminalRuleCall_3; }

		//CHARLITERAL
		public RuleCall getCHARLITERALTerminalRuleCall_4() { return cCHARLITERALTerminalRuleCall_4; }

		//STRINGLITERAL
		public RuleCall getSTRINGLITERALTerminalRuleCall_5() { return cSTRINGLITERALTerminalRuleCall_5; }

		//TRUE
		public RuleCall getTRUETerminalRuleCall_6() { return cTRUETerminalRuleCall_6; }

		//FALSE
		public RuleCall getFALSETerminalRuleCall_7() { return cFALSETerminalRuleCall_7; }

		//NULL
		public RuleCall getNULLTerminalRuleCall_8() { return cNULLTerminalRuleCall_8; }
	}

	public class PrimitiveTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimitiveType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cBooleanKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cCharKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cByteKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cShortKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cIntKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cLongKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cFloatKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		private final Keyword cDoubleKeyword_7 = (Keyword)cAlternatives.eContents().get(7);
		
		//PrimitiveType:
		//	"boolean" | "char" | "byte" | "short" | "int" | "long" | "float" | "double";
		public ParserRule getRule() { return rule; }

		//"boolean" | "char" | "byte" | "short" | "int" | "long" | "float" | "double"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"boolean"
		public Keyword getBooleanKeyword_0() { return cBooleanKeyword_0; }

		//"char"
		public Keyword getCharKeyword_1() { return cCharKeyword_1; }

		//"byte"
		public Keyword getByteKeyword_2() { return cByteKeyword_2; }

		//"short"
		public Keyword getShortKeyword_3() { return cShortKeyword_3; }

		//"int"
		public Keyword getIntKeyword_4() { return cIntKeyword_4; }

		//"long"
		public Keyword getLongKeyword_5() { return cLongKeyword_5; }

		//"float"
		public Keyword getFloatKeyword_6() { return cFloatKeyword_6; }

		//"double"
		public Keyword getDoubleKeyword_7() { return cDoubleKeyword_7; }
	}
	
	
	private ModelElements pModel;
	private ExpressionElements pExpression;
	private MethodInvocationElements pMethodInvocation;
	private BaseJRExprElements pBaseJRExpr;
	private ArgumentsElements pArguments;
	private ExpressionListElements pExpressionList;
	private BaseCommonExpressionElements pBaseCommonExpression;
	private CastElements pCast;
	private ConditionalExpressionElements pConditionalExpression;
	private TestExpressionElements pTestExpression;
	private OrExpressionElements pOrExpression;
	private AndExpressionElements pAndExpression;
	private PrimaryCondExpressionElements pPrimaryCondExpression;
	private BaseBooleanExprElements pBaseBooleanExpr;
	private EqualityExpressionElements pEqualityExpression;
	private RelationalExpressionElements pRelationalExpression;
	private InstanceOfExpressionElements pInstanceOfExpression;
	private AdditiveExpressionElements pAdditiveExpression;
	private MultiplicativeExpressionElements pMultiplicativeExpression;
	private RelationalOpElements pRelationalOp;
	private CreatorElements pCreator;
	private ClassCreatorElements pClassCreator;
	private ArrayCreatorElements pArrayCreator;
	private ArrayInitializerElements pArrayInitializer;
	private InnerCreatorElements pInnerCreator;
	private ArrayTypeElements pArrayType;
	private ClassOrInterfaceTypeElements pClassOrInterfaceType;
	private QualifiedNameElements pQualifiedName;
	private LiteralElements pLiteral;
	private PrimitiveTypeElements pPrimitiveType;
	private TerminalRule tFieldToken;
	private TerminalRule tVariableToken;
	private TerminalRule tParameterToken;
	private TerminalRule tBRACED_JRIDENTIFIER;
	private TerminalRule tLONGLITERAL;
	private TerminalRule tINTLITERAL;
	private TerminalRule tIntegerNumber;
	private TerminalRule tHexPrefix;
	private TerminalRule tHexDigit;
	private TerminalRule tLongSuffix;
	private TerminalRule tNonIntegerNumber;
	private TerminalRule tExponent;
	private TerminalRule tFloatSuffix;
	private TerminalRule tDoubleSuffix;
	private TerminalRule tFLOATLITERAL;
	private TerminalRule tDOUBLELITERAL;
	private TerminalRule tCHARLITERAL;
	private TerminalRule tSTRINGLITERAL;
	private TerminalRule tEscapeSequence;
	private TerminalRule tTRUE;
	private TerminalRule tFALSE;
	private TerminalRule tNULL;
	private TerminalRule tLPAREN;
	private TerminalRule tRPAREN;
	private TerminalRule tLBRACE;
	private TerminalRule tRBRACE;
	private TerminalRule tLBRACKET;
	private TerminalRule tRBRACKET;
	private TerminalRule tSEMI;
	private TerminalRule tCOMMA;
	private TerminalRule tDOT;
	private TerminalRule tNOTEQUAL;
	private TerminalRule tEQUAL;
	private TerminalRule tGT;
	private TerminalRule tGTE;
	private TerminalRule tLT;
	private TerminalRule tLTE;
	private TerminalRule tNEW;
	private TerminalRule tINSTANCEOF;
	private TerminalRule tNOT;
	private TerminalRule tIDENTIFIER;
	private TerminalRule tLETTER;
	private TerminalRule tJavaIDDigit;
	private TerminalRule tJRIDENTIFIER;
	private TerminalRule tML_COMMENT;
	private TerminalRule tSL_COMMENT;
	private TerminalRule tWS;
	
	private final GrammarProvider grammarProvider;

	@Inject
	public JavaJRExpressionGrammarAccess(GrammarProvider grammarProvider) {
		this.grammarProvider = grammarProvider;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	
	//Model:
	//	Expression;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Expression:
	//	Creator | Cast? condExpr=ConditionalExpression;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//MethodInvocation:
	//	methodName=QualifiedName args=Arguments;
	public MethodInvocationElements getMethodInvocationAccess() {
		return (pMethodInvocation != null) ? pMethodInvocation : (pMethodInvocation = new MethodInvocationElements());
	}
	
	public ParserRule getMethodInvocationRule() {
		return getMethodInvocationAccess().getRule();
	}

	//BaseJRExpr:
	//	fieldToken=FieldToken | parameterToken=ParameterToken | variableToken=VariableToken;
	public BaseJRExprElements getBaseJRExprAccess() {
		return (pBaseJRExpr != null) ? pBaseJRExpr : (pBaseJRExpr = new BaseJRExprElements());
	}
	
	public ParserRule getBaseJRExprRule() {
		return getBaseJRExprAccess().getRule();
	}

	//Arguments:
	//	leftP=LPAREN exprLst=ExpressionList? rightP=RPAREN;
	public ArgumentsElements getArgumentsAccess() {
		return (pArguments != null) ? pArguments : (pArguments = new ArgumentsElements());
	}
	
	public ParserRule getArgumentsRule() {
		return getArgumentsAccess().getRule();
	}

	//ExpressionList:
	//	expressions+=Expression (commas+=COMMA expressions+=Expression)*;
	public ExpressionListElements getExpressionListAccess() {
		return (pExpressionList != null) ? pExpressionList : (pExpressionList = new ExpressionListElements());
	}
	
	public ParserRule getExpressionListRule() {
		return getExpressionListAccess().getRule();
	}

	//BaseCommonExpression returns Expression:
	//	basejrexpr=BaseJRExpr | literal=Literal | LPAREN Expression RPAREN | MethodInvocation;
	public BaseCommonExpressionElements getBaseCommonExpressionAccess() {
		return (pBaseCommonExpression != null) ? pBaseCommonExpression : (pBaseCommonExpression = new BaseCommonExpressionElements());
	}
	
	public ParserRule getBaseCommonExpressionRule() {
		return getBaseCommonExpressionAccess().getRule();
	}

	//Cast:
	//	lpar=LPAREN (ptype=PrimitiveType | arrtype=ArrayType | clazztype=ClassOrInterfaceType) rpar=RPAREN;
	public CastElements getCastAccess() {
		return (pCast != null) ? pCast : (pCast = new CastElements());
	}
	
	public ParserRule getCastRule() {
		return getCastAccess().getRule();
	}

	////primary:
	////	parExpression=parExpression
	////	| this='this'
	////	(dot+=DOT identifier+=IDENTIFIER)*
	////	(identifierSuffix=identifierSuffix)?
	////	| identifier+=IDENTIFIER
	////	(dot+=DOT identifier+=IDENTIFIER)*
	////	(identifierSuffix=identifierSuffix)?
	////	| 'super'
	////	superSuffix=superSuffix
	////	| literal=Literal
	////	| creator=Creator
	////	| primitiveType=PrimitiveType
	////	(lbrack+=LBRACKET rbrack+=RBRACKET)*
	////	dot+=DOT 'class'
	////	| 'void' dot+=DOT 'class';
	//// ========================== CONDITIONAL EXPRESSION STUFF ========================== //
	//ConditionalExpression returns Expression:
	//	TestExpression ("?" okReturnedExpr=Expression ":" koReturnedExpr=Expression)?;
	public ConditionalExpressionElements getConditionalExpressionAccess() {
		return (pConditionalExpression != null) ? pConditionalExpression : (pConditionalExpression = new ConditionalExpressionElements());
	}
	
	public ParserRule getConditionalExpressionRule() {
		return getConditionalExpressionAccess().getRule();
	}

	//TestExpression returns Expression:
	//	OrExpression;
	public TestExpressionElements getTestExpressionAccess() {
		return (pTestExpression != null) ? pTestExpression : (pTestExpression = new TestExpressionElements());
	}
	
	public ParserRule getTestExpressionRule() {
		return getTestExpressionAccess().getRule();
	}

	//OrExpression returns Expression:
	//	andExp+=AndExpression ("||" andExp+=AndExpression)*;
	public OrExpressionElements getOrExpressionAccess() {
		return (pOrExpression != null) ? pOrExpression : (pOrExpression = new OrExpressionElements());
	}
	
	public ParserRule getOrExpressionRule() {
		return getOrExpressionAccess().getRule();
	}

	//AndExpression returns Expression:
	//	primaryCond+=PrimaryCondExpression ("&&" primaryCond+=PrimaryCondExpression)*;
	public AndExpressionElements getAndExpressionAccess() {
		return (pAndExpression != null) ? pAndExpression : (pAndExpression = new AndExpressionElements());
	}
	
	public ParserRule getAndExpressionRule() {
		return getAndExpressionAccess().getRule();
	}

	//PrimaryCondExpression returns Expression:
	//	expr=BaseBooleanExpr;
	public PrimaryCondExpressionElements getPrimaryCondExpressionAccess() {
		return (pPrimaryCondExpression != null) ? pPrimaryCondExpression : (pPrimaryCondExpression = new PrimaryCondExpressionElements());
	}
	
	public ParserRule getPrimaryCondExpressionRule() {
		return getPrimaryCondExpressionAccess().getRule();
	}

	//BaseBooleanExpr returns Expression:
	//	NOT? EqualityExpression;
	public BaseBooleanExprElements getBaseBooleanExprAccess() {
		return (pBaseBooleanExpr != null) ? pBaseBooleanExpr : (pBaseBooleanExpr = new BaseBooleanExprElements());
	}
	
	public ParserRule getBaseBooleanExprRule() {
		return getBaseBooleanExprAccess().getRule();
	}

	//// ========================== COMPARE EXPRESSIONS STUFF ========================== //
	//EqualityExpression returns Expression:
	//	instanceof+=InstanceOfExpression ((EQUAL | NOTEQUAL) instanceof+=InstanceOfExpression)*;
	public EqualityExpressionElements getEqualityExpressionAccess() {
		return (pEqualityExpression != null) ? pEqualityExpression : (pEqualityExpression = new EqualityExpressionElements());
	}
	
	public ParserRule getEqualityExpressionRule() {
		return getEqualityExpressionAccess().getRule();
	}

	//RelationalExpression returns Expression:
	//	rel+=AdditiveExpression (RelationalOp rel+=AdditiveExpression)*;
	public RelationalExpressionElements getRelationalExpressionAccess() {
		return (pRelationalExpression != null) ? pRelationalExpression : (pRelationalExpression = new RelationalExpressionElements());
	}
	
	public ParserRule getRelationalExpressionRule() {
		return getRelationalExpressionAccess().getRule();
	}

	//InstanceOfExpression returns Expression:
	//	el=RelationalExpression (INSTANCEOF target=(RelationalExpression | ClassOrInterfaceType))?;
	public InstanceOfExpressionElements getInstanceOfExpressionAccess() {
		return (pInstanceOfExpression != null) ? pInstanceOfExpression : (pInstanceOfExpression = new InstanceOfExpressionElements());
	}
	
	public ParserRule getInstanceOfExpressionRule() {
		return getInstanceOfExpressionAccess().getRule();
	}

	//AdditiveExpression returns Expression:
	//	multExpr+=MultiplicativeExpression (("+" | "-") multExpr+=MultiplicativeExpression)*;
	public AdditiveExpressionElements getAdditiveExpressionAccess() {
		return (pAdditiveExpression != null) ? pAdditiveExpression : (pAdditiveExpression = new AdditiveExpressionElements());
	}
	
	public ParserRule getAdditiveExpressionRule() {
		return getAdditiveExpressionAccess().getRule();
	}

	//MultiplicativeExpression returns Expression:
	//	baseExpr+=BaseCommonExpression (DOT methods+=MethodInvocation)* (("*" | "/") baseExpr+=BaseCommonExpression (DOT
	//	methods+=MethodInvocation)*)*;
	public MultiplicativeExpressionElements getMultiplicativeExpressionAccess() {
		return (pMultiplicativeExpression != null) ? pMultiplicativeExpression : (pMultiplicativeExpression = new MultiplicativeExpressionElements());
	}
	
	public ParserRule getMultiplicativeExpressionRule() {
		return getMultiplicativeExpressionAccess().getRule();
	}

	//RelationalOp:
	//	GT | GTE | LT | LTE;
	public RelationalOpElements getRelationalOpAccess() {
		return (pRelationalOp != null) ? pRelationalOp : (pRelationalOp = new RelationalOpElements());
	}
	
	public ParserRule getRelationalOpRule() {
		return getRelationalOpAccess().getRule();
	}

	////conditionalExpression:
	////	conditionalOrExpression=conditionalOrExpression
	////	('?' expression=Expression ':' conditionalExpression=conditionalExpression)?;
	////
	////conditionalOrExpression:
	////	conditionalAndExpression+=conditionalAndExpression
	////	('||' conditionalAndExpression+=conditionalAndExpression)*;
	////
	////conditionalAndExpression:
	////	inclusiveOrExpression+=inclusiveOrExpression
	////	('&&' inclusiveOrExpression+=inclusiveOrExpression)*;
	////
	////inclusiveOrExpression:
	////	exclusiveOrExpression+=exclusiveOrExpression
	////	('|' exclusiveOrExpression+=exclusiveOrExpression)*;
	////
	////exclusiveOrExpression:
	////	andExpression+=andExpression
	////	('^' andExpression+=andExpression)*;
	////
	////andExpression:
	////	equalityExpression+=equalityExpression
	////	('&' equalityExpression+=equalityExpression)*;
	////
	////equalityExpression:
	////	instanceOfExpression+=InstanceOfExpression
	////	(('=='
	////	| '!=')
	////	instanceOfExpression+=InstanceOfExpression)*;
	////
	////InstanceOfExpression:
	////	relationalExpression=relationalExpression
	////	('instanceof' type=Type)?;
	////
	////relationalExpression:
	////	shiftExpression+=shiftExpression
	////	(relationalOp shiftExpression+=shiftExpression)*;
	////
	////terminal relationalOp:
	////	'<' '='
	////	| '>' '='
	////	| '<'
	////	| '>';
	////
	////shiftExpression 
	////    :   additiveExpression+=additiveExpression
	////        (shiftOp additiveExpression+=additiveExpression
	////        )*
	////    ;
	////
	////terminal shiftOp:
	////	'<' '<'
	////	| '>' '>' '>'
	////	| '>' '>';
	////
	////
	////additiveExpression:
	////	multiplicativeExpression+=multiplicativeExpression
	////	(('+'
	////	| '-')
	////	multiplicativeExpression+=multiplicativeExpression)*;
	////
	////multiplicativeExpression:
	////	unaryExpression+=unaryExpression
	////	(('*'
	////	| '/'
	////	| '%')
	////	unaryExpression+=unaryExpression)*;
	////
	///// **
	//// * NOTE: for '+' and '-', if the next token is int or long interal, then it's not a unary expression.
	//// *       it's a literal with signed value. INTLTERAL AND LONG LITERAL are added here for this.
	//// * /
	////unaryExpression:
	////	'+' unaryExpression=unaryExpression
	////	| '-' unaryExpression=unaryExpression
	////	| '++' unaryExpression=unaryExpression
	////	| '--' unaryExpression=unaryExpression
	////	| unaryExpressionNotPlusMinus;
	////
	////unaryExpressionNotPlusMinus:
	////	'~' unaryExpression=unaryExpression
	////	| '!' unaryExpression=unaryExpression
	////	| castExpression=CastExpression
	////	| primary
	////	(selector+=selector)*
	////	('++'
	////	| '--')?;
	////	
	////primary:
	////	parExpression=parExpression
	////	| this='this'
	////	(dot+=DOT identifier+=IDENTIFIER)*
	////	(identifierSuffix=identifierSuffix)?
	////	| identifier+=IDENTIFIER
	////	(dot+=DOT identifier+=IDENTIFIER)*
	////	(identifierSuffix=identifierSuffix)?
	////	| 'super'
	////	superSuffix=superSuffix
	////	| literal=Literal
	////	| creator=Creator
	////	| primitiveType=PrimitiveType
	////	(lbrack+=LBRACKET rbrack+=RBRACKET)*
	////	dot+=DOT 'class'
	////	| 'void' dot+=DOT 'class';
	////
	////parExpression 
	////    :   LPAREN Expression RPAREN
	////    ;
	////
	////superSuffix:
	////	Arguments
	////	| dot=DOT
	////	identifier=IDENTIFIER
	////	(arguments=Arguments)?;
	////
	////
	////identifierSuffix:
	////	(LBRACKET RBRACKET)+
	////	dot+=DOT 'class'
	////	| (LBRACKET expression+=Expression RBRACKET)+
	////	| arguments=Arguments
	////	| dot+=DOT 'class'
	////	| dot+=DOT IDENTIFIER arguments=Arguments
	////	| dot+=DOT 'this'
	////	| dot+=DOT 'super' arguments=Arguments
	////	| innerCreator=InnerCreator;
	////
	////selector:
	////	dot=DOT identifier=IDENTIFIER
	////	(arguments=Arguments)?
	////	| dot=DOT 'this'
	////	| dot=DOT 'super'
	////	superSuffix=superSuffix
	////	| innerCreator=InnerCreator
	////	| LBRACKET expression=Expression RBRACKET;	
	//Creator:
	//	ClassCreator | ArrayCreator;
	public CreatorElements getCreatorAccess() {
		return (pCreator != null) ? pCreator : (pCreator = new CreatorElements());
	}
	
	public ParserRule getCreatorRule() {
		return getCreatorAccess().getRule();
	}

	//ClassCreator:
	//	NEW clazz=ClassOrInterfaceType args=Arguments;
	public ClassCreatorElements getClassCreatorAccess() {
		return (pClassCreator != null) ? pClassCreator : (pClassCreator = new ClassCreatorElements());
	}
	
	public ParserRule getClassCreatorRule() {
		return getClassCreatorAccess().getRule();
	}

	//ArrayCreator:
	//	NEW type=ArrayType arrayInitializer=ArrayInitializer;
	public ArrayCreatorElements getArrayCreatorAccess() {
		return (pArrayCreator != null) ? pArrayCreator : (pArrayCreator = new ArrayCreatorElements());
	}
	
	public ParserRule getArrayCreatorRule() {
		return getArrayCreatorAccess().getRule();
	}

	//ArrayInitializer:
	//	{ArrayInitializer} LBRACE (firstEl=Expression (COMMA otherEls+=Expression)*)? COMMA? RBRACE;
	public ArrayInitializerElements getArrayInitializerAccess() {
		return (pArrayInitializer != null) ? pArrayInitializer : (pArrayInitializer = new ArrayInitializerElements());
	}
	
	public ParserRule getArrayInitializerRule() {
		return getArrayInitializerAccess().getRule();
	}

	//InnerCreator:
	//	DOT NEW IDENTIFIER args=Arguments;
	public InnerCreatorElements getInnerCreatorAccess() {
		return (pInnerCreator != null) ? pInnerCreator : (pInnerCreator = new InnerCreatorElements());
	}
	
	public ParserRule getInnerCreatorRule() {
		return getInnerCreatorAccess().getRule();
	}

	//ArrayType:
	//	(clazzInterf=ClassOrInterfaceType | primtype=PrimitiveType) (LBRACKET RBRACKET)+;
	public ArrayTypeElements getArrayTypeAccess() {
		return (pArrayType != null) ? pArrayType : (pArrayType = new ArrayTypeElements());
	}
	
	public ParserRule getArrayTypeRule() {
		return getArrayTypeAccess().getRule();
	}

	//ClassOrInterfaceType:
	//	qualifiedName=QualifiedName;
	public ClassOrInterfaceTypeElements getClassOrInterfaceTypeAccess() {
		return (pClassOrInterfaceType != null) ? pClassOrInterfaceType : (pClassOrInterfaceType = new ClassOrInterfaceTypeElements());
	}
	
	public ParserRule getClassOrInterfaceTypeRule() {
		return getClassOrInterfaceTypeAccess().getRule();
	}

	//QualifiedName:
	//	{QualifiedName} identifier+=IDENTIFIER (dot+=DOT identifier+=IDENTIFIER)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return (pQualifiedName != null) ? pQualifiedName : (pQualifiedName = new QualifiedNameElements());
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Literal:
	//	INTLITERAL | LONGLITERAL | FLOATLITERAL | DOUBLELITERAL | CHARLITERAL | STRINGLITERAL | TRUE | FALSE | NULL;
	public LiteralElements getLiteralAccess() {
		return (pLiteral != null) ? pLiteral : (pLiteral = new LiteralElements());
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}

	//PrimitiveType:
	//	"boolean" | "char" | "byte" | "short" | "int" | "long" | "float" | "double";
	public PrimitiveTypeElements getPrimitiveTypeAccess() {
		return (pPrimitiveType != null) ? pPrimitiveType : (pPrimitiveType = new PrimitiveTypeElements());
	}
	
	public ParserRule getPrimitiveTypeRule() {
		return getPrimitiveTypeAccess().getRule();
	}

	//terminal FieldToken:
	//	"$F" BRACED_JRIDENTIFIER;
	public TerminalRule getFieldTokenRule() {
		return (tFieldToken != null) ? tFieldToken : (tFieldToken = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "FieldToken"));
	} 

	//terminal VariableToken:
	//	"$V" BRACED_JRIDENTIFIER;
	public TerminalRule getVariableTokenRule() {
		return (tVariableToken != null) ? tVariableToken : (tVariableToken = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "VariableToken"));
	} 

	//terminal ParameterToken:
	//	"$P" BRACED_JRIDENTIFIER;
	public TerminalRule getParameterTokenRule() {
		return (tParameterToken != null) ? tParameterToken : (tParameterToken = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterToken"));
	} 

	//// ============= TERMINAL RULES ============= //
	//terminal fragment BRACED_JRIDENTIFIER:
	//	LBRACE JRIDENTIFIER RBRACE;
	public TerminalRule getBRACED_JRIDENTIFIERRule() {
		return (tBRACED_JRIDENTIFIER != null) ? tBRACED_JRIDENTIFIER : (tBRACED_JRIDENTIFIER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "BRACED_JRIDENTIFIER"));
	} 

	//terminal LONGLITERAL:
	//	IntegerNumber LongSuffix;
	public TerminalRule getLONGLITERALRule() {
		return (tLONGLITERAL != null) ? tLONGLITERAL : (tLONGLITERAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LONGLITERAL"));
	} 

	//terminal INTLITERAL:
	//	IntegerNumber;
	public TerminalRule getINTLITERALRule() {
		return (tINTLITERAL != null) ? tINTLITERAL : (tINTLITERAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INTLITERAL"));
	} 

	//terminal fragment IntegerNumber:
	//	"0" | "1".."9" "0".."9"* | "0" "0".."7"+ | HexPrefix HexDigit+;
	public TerminalRule getIntegerNumberRule() {
		return (tIntegerNumber != null) ? tIntegerNumber : (tIntegerNumber = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "IntegerNumber"));
	} 

	//terminal fragment HexPrefix:
	//	"0x" | "0X";
	public TerminalRule getHexPrefixRule() {
		return (tHexPrefix != null) ? tHexPrefix : (tHexPrefix = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "HexPrefix"));
	} 

	//terminal fragment HexDigit:
	//	"0".."9" | "a".."f" | "A".."F";
	public TerminalRule getHexDigitRule() {
		return (tHexDigit != null) ? tHexDigit : (tHexDigit = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "HexDigit"));
	} 

	//terminal fragment LongSuffix:
	//	"l" | "L";
	public TerminalRule getLongSuffixRule() {
		return (tLongSuffix != null) ? tLongSuffix : (tLongSuffix = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LongSuffix"));
	} 

	//terminal fragment NonIntegerNumber:
	//	"0".."9"+ "." "0".."9"* Exponent? | "." "0".."9"+ Exponent? | "0".."9"+ Exponent | "0".."9"+ | HexPrefix HexDigit*
	//	("." HexDigit*) ("p" | "P") ("+" | "-")? "0".."9"+;
	public TerminalRule getNonIntegerNumberRule() {
		return (tNonIntegerNumber != null) ? tNonIntegerNumber : (tNonIntegerNumber = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NonIntegerNumber"));
	} 

	//terminal fragment Exponent:
	//	("e" | "E") ("+" | "-")? "0".."9"+;
	public TerminalRule getExponentRule() {
		return (tExponent != null) ? tExponent : (tExponent = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "Exponent"));
	} 

	//terminal fragment FloatSuffix:
	//	"f" | "F";
	public TerminalRule getFloatSuffixRule() {
		return (tFloatSuffix != null) ? tFloatSuffix : (tFloatSuffix = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "FloatSuffix"));
	} 

	//terminal fragment DoubleSuffix:
	//	"d" | "D";
	public TerminalRule getDoubleSuffixRule() {
		return (tDoubleSuffix != null) ? tDoubleSuffix : (tDoubleSuffix = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DoubleSuffix"));
	} 

	//terminal FLOATLITERAL:
	//	NonIntegerNumber FloatSuffix;
	public TerminalRule getFLOATLITERALRule() {
		return (tFLOATLITERAL != null) ? tFLOATLITERAL : (tFLOATLITERAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "FLOATLITERAL"));
	} 

	//terminal DOUBLELITERAL:
	//	NonIntegerNumber DoubleSuffix?;
	public TerminalRule getDOUBLELITERALRule() {
		return (tDOUBLELITERAL != null) ? tDOUBLELITERAL : (tDOUBLELITERAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DOUBLELITERAL"));
	} 

	//terminal CHARLITERAL:
	//	"\'" (EscapeSequence | !("\'" | "\\" | "\r" | "\n")) "\'";
	public TerminalRule getCHARLITERALRule() {
		return (tCHARLITERAL != null) ? tCHARLITERAL : (tCHARLITERAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "CHARLITERAL"));
	} 

	//terminal STRINGLITERAL:
	//	"\"" (EscapeSequence | !("\\" | "\"" | "\r" | "\n"))* "\"";
	public TerminalRule getSTRINGLITERALRule() {
		return (tSTRINGLITERAL != null) ? tSTRINGLITERAL : (tSTRINGLITERAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "STRINGLITERAL"));
	} 

	//terminal fragment EscapeSequence:
	//	"\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\" | "0".."3" "0".."7" "0".."7" | "0".."7" "0".."7" | "0".."7");
	public TerminalRule getEscapeSequenceRule() {
		return (tEscapeSequence != null) ? tEscapeSequence : (tEscapeSequence = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "EscapeSequence"));
	} 

	//terminal TRUE:
	//	"true";
	public TerminalRule getTRUERule() {
		return (tTRUE != null) ? tTRUE : (tTRUE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TRUE"));
	} 

	//terminal FALSE:
	//	"false";
	public TerminalRule getFALSERule() {
		return (tFALSE != null) ? tFALSE : (tFALSE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "FALSE"));
	} 

	//terminal NULL:
	//	"null";
	public TerminalRule getNULLRule() {
		return (tNULL != null) ? tNULL : (tNULL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NULL"));
	} 

	//terminal LPAREN:
	//	"(";
	public TerminalRule getLPARENRule() {
		return (tLPAREN != null) ? tLPAREN : (tLPAREN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LPAREN"));
	} 

	//terminal RPAREN:
	//	")";
	public TerminalRule getRPARENRule() {
		return (tRPAREN != null) ? tRPAREN : (tRPAREN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RPAREN"));
	} 

	//terminal LBRACE:
	//	"{";
	public TerminalRule getLBRACERule() {
		return (tLBRACE != null) ? tLBRACE : (tLBRACE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LBRACE"));
	} 

	//terminal RBRACE:
	//	"}";
	public TerminalRule getRBRACERule() {
		return (tRBRACE != null) ? tRBRACE : (tRBRACE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RBRACE"));
	} 

	//terminal LBRACKET:
	//	"[";
	public TerminalRule getLBRACKETRule() {
		return (tLBRACKET != null) ? tLBRACKET : (tLBRACKET = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LBRACKET"));
	} 

	//terminal RBRACKET:
	//	"]";
	public TerminalRule getRBRACKETRule() {
		return (tRBRACKET != null) ? tRBRACKET : (tRBRACKET = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RBRACKET"));
	} 

	//terminal SEMI:
	//	";";
	public TerminalRule getSEMIRule() {
		return (tSEMI != null) ? tSEMI : (tSEMI = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SEMI"));
	} 

	//terminal COMMA:
	//	",";
	public TerminalRule getCOMMARule() {
		return (tCOMMA != null) ? tCOMMA : (tCOMMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COMMA"));
	} 

	//terminal DOT:
	//	".";
	public TerminalRule getDOTRule() {
		return (tDOT != null) ? tDOT : (tDOT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DOT"));
	} 

	//terminal NOTEQUAL:
	//	"!=";
	public TerminalRule getNOTEQUALRule() {
		return (tNOTEQUAL != null) ? tNOTEQUAL : (tNOTEQUAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NOTEQUAL"));
	} 

	//terminal EQUAL:
	//	"==";
	public TerminalRule getEQUALRule() {
		return (tEQUAL != null) ? tEQUAL : (tEQUAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "EQUAL"));
	} 

	//terminal GT:
	//	">";
	public TerminalRule getGTRule() {
		return (tGT != null) ? tGT : (tGT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "GT"));
	} 

	//terminal GTE:
	//	">=";
	public TerminalRule getGTERule() {
		return (tGTE != null) ? tGTE : (tGTE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "GTE"));
	} 

	//terminal LT:
	//	"<";
	public TerminalRule getLTRule() {
		return (tLT != null) ? tLT : (tLT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LT"));
	} 

	//terminal LTE:
	//	"<=";
	public TerminalRule getLTERule() {
		return (tLTE != null) ? tLTE : (tLTE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LTE"));
	} 

	//terminal NEW:
	//	"new";
	public TerminalRule getNEWRule() {
		return (tNEW != null) ? tNEW : (tNEW = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NEW"));
	} 

	//terminal INSTANCEOF:
	//	"instanceof";
	public TerminalRule getINSTANCEOFRule() {
		return (tINSTANCEOF != null) ? tINSTANCEOF : (tINSTANCEOF = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INSTANCEOF"));
	} 

	//terminal NOT:
	//	"!";
	public TerminalRule getNOTRule() {
		return (tNOT != null) ? tNOT : (tNOT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NOT"));
	} 

	//terminal IDENTIFIER:
	//	LETTER (LETTER | JavaIDDigit)*;
	public TerminalRule getIDENTIFIERRule() {
		return (tIDENTIFIER != null) ? tIDENTIFIER : (tIDENTIFIER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "IDENTIFIER"));
	} 

	//terminal fragment LETTER:
	//	"$" | "A".."Z" | "_" | "a".."z" | "Ë".."…" | "¯".."š" | "¿".."Ø" | "?".."?" | "?".."?" | "?".."?" | "?".."?" |
	//	"?".."?" | "?".."?";
	public TerminalRule getLETTERRule() {
		return (tLETTER != null) ? tLETTER : (tLETTER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LETTER"));
	} 

	//terminal fragment JavaIDDigit:
	//	"0".."9" | "?".."?" | "?".."?" | "?".."?" | "?".."?" | "?".."?" | "?".."?" | "?".."?" | "?".."?" | "?".."?" | "?".."?"
	//	| "?".."?" | "?".."?" | "?".."?" | "?".."?";
	public TerminalRule getJavaIDDigitRule() {
		return (tJavaIDDigit != null) ? tJavaIDDigit : (tJavaIDDigit = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "JavaIDDigit"));
	} 

	//terminal fragment JRIDENTIFIER:
	//	!("\r" | "\n" | "}")+;
	public TerminalRule getJRIDENTIFIERRule() {
		return (tJRIDENTIFIER != null) ? tJRIDENTIFIER : (tJRIDENTIFIER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "JRIDENTIFIER"));
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return (tML_COMMENT != null) ? tML_COMMENT : (tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ML_COMMENT"));
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return (tSL_COMMENT != null) ? tSL_COMMENT : (tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SL_COMMENT"));
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return (tWS != null) ? tWS : (tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS"));
	} 
}
