/*
* generated by Xtext
*/
package com.jaspersoft.studio.editor.jrexpressions.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JavaJRExpressionProposalProvider extends AbstractJavaJRExpressionProposalProvider {
	
	@Override
	public void complete_FieldToken(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		// TODO - ADD LOGIC TO RETRIEVE AND PROPOSE THE FIELDS
	}
	
	@Override
	public void complete_VariableToken(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		// TODO - ADD LOGIC TO RETRIEVE AND PROPOSE THE VARIABLES
	}
	
	@Override
	public void complete_ParameterToken(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		// TODO - ADD LOGIC TO RETRIEVE AND PROPOSE THE PARAMETERS
//		acceptor.accept(createCompletionProposal(  
//			      "$P{TEST PARAM1}", "$P{TEST PARAM1}",  
//			      getParameterIconImg(), context));  
//			    acceptor.accept(createCompletionProposal(  
//			      "$P{TEST PARAM2}", "$P{TEST PARAM2}",  
//			      getParameterIconImg(), context)); 
	}

}
